# Fetching Facility Data

Reverse engineering Yale's energy usage website

In [1]:
import json
import re

import polars as pl
import requests
from bs4 import BeautifulSoup

In [2]:
response = requests.get("https://java.facilities.yale.edu/energy/")

In [3]:
soup = BeautifulSoup(response.text, "html.parser")

script_text = soup.find("script", string=re.compile("var user")).string

# extract JSON parts
user_json = re.search(r'var user\s*=\s*(\{.*?\});', script_text, re.S).group(1)
buildings_json = re.search(r'var buildings\s*=\s*(\[.*?\]);', script_text, re.S).group(1)

user = json.loads(user_json)
buildings = json.loads(buildings_json)

# print(user)
# print(buildings)

In [4]:
rows = []

for s in user["sets"]:
    set_meta = {
        "bsID": s["bsID"],
        "bsName": s["bsName"],
        "bsDescription": s.get("bsDescription"),
        "bsPublic": s["bsPublic"],
        "owner": s["owner"],
        "sort": s["sort"]
    }

    for b in s["buildings"]:
        row = {**set_meta, **b}
        rows.append(row)

df = pl.DataFrame(rows)

In [5]:
facilities = (
    df
    .unique(subset=["facid"])
    .select([
        "facid",
        "site",
        "name",
        "address",
        "zone",
        "owned",
        "status",
        "latitude",
        "longitude"
    ])
    .sort("facid")
)
building_sets = (
    df
    .unique(subset=["bsID"])
    .select([
        "bsID",
        "bsName",
        "bsDescription",
        "bsPublic",
        "owner",
        "sort"
    ])
    .sort("bsID")
)
membership = (
    df
    .select(["facid", "bsID"])
    .unique()
    .sort(["facid", "bsID"])
)

In [6]:
facilities

shape: (370, 9)
┌───────┬──────┬──────────────────┬──────────────────┬───┬───────┬────────┬───────────┬────────────┐
│ facid ┆ site ┆ name             ┆ address          ┆ … ┆ owned ┆ status ┆ latitude  ┆ longitude  │
│ ---   ┆ ---  ┆ ---              ┆ ---              ┆   ┆ ---   ┆ ---    ┆ ---       ┆ ---        │
│ str   ┆ str  ┆ str              ┆ str              ┆   ┆ str   ┆ str    ┆ f64       ┆ f64        │
╞═══════╪══════╪══════════════════╪══════════════════╪═══╪═══════╪════════╪═══════════╪════════════╡
│ 0000  ┆ CEN  ┆ FAC ID-NON-BLDG  ┆ NOT APPLICABLE   ┆ … ┆ null  ┆ OPEN   ┆ null      ┆ null       │
│       ┆      ┆ ORGS             ┆                  ┆   ┆       ┆        ┆           ┆            │
│ 0110  ┆ CEN  ┆ CALVIN HILL DAY  ┆ HIGHLAND STREET, ┆ … ┆ OO    ┆ OPEN   ┆ 41.328181 ┆ -72.920866 │
│       ┆      ┆ CARE             ┆ 150              ┆   ┆       ┆        ┆           ┆            │
│ 0120  ┆ CEN  ┆ WHITEHALL APTS   ┆ CANNER STREET,   ┆ … ┆ OO    ┆ OPEN   ┆ 41.325814 ┆ -72.921398 │
│       ┆      ┆ 375-385          ┆ 375-385          ┆   ┆       ┆        ┆           ┆            │
│ 0122  ┆ CEN  ┆ WHITEHALL APTS   ┆ CANNER STREET,   ┆ … ┆ OO    ┆ OPEN   ┆ 41.326013 ┆ -72.922116 │
│       ┆      ┆ 405-407          ┆ 405-407          ┆   ┆       ┆        ┆           ┆            │
│ 0124  ┆ CEN  ┆ WHITEHALL APTS   ┆ PROSPECT STREET, ┆ … ┆ OO    ┆ OPEN   ┆ 41.326293 ┆ -72.921995 │
│       ┆      ┆ 511-521          ┆ 511-521          ┆   ┆       ┆        ┆           ┆            │
│ …     ┆ …    ┆ …                ┆ …                ┆ … ┆ …     ┆ …      ┆ …         ┆ …          │
│ 4245  ┆ WST  ┆ WC ENERGY        ┆ WEST CAMPUS      ┆ … ┆ OO    ┆ OPEN   ┆ 41.258284 ┆ -72.990042 │
│       ┆      ┆ SCIENCES CTR     ┆ DRIVE, 520       ┆   ┆       ┆        ┆           ┆            │
│ 4250  ┆ WST  ┆ WC COLLECTION ST ┆ WEST CAMPUS      ┆ … ┆ OO    ┆ OPEN   ┆ 41.259342 ┆ -72.987395 │
│       ┆      ┆ CTR              ┆ DRIVE, 900       ┆   ┆       ┆        ┆           ┆            │
│ 4270  ┆ WST  ┆ WC STORAGE &     ┆ WEST CAMPUS      ┆ … ┆ OO    ┆ OPEN   ┆ 41.257826 ┆ -72.985888 │
│       ┆      ┆ RECEIV CTR       ┆ DRIVE, 750       ┆   ┆       ┆        ┆           ┆            │
│ 4272  ┆ WST  ┆ WC ENVIR HL &    ┆ WEST CAMPUS      ┆ … ┆ OO    ┆ OPEN   ┆ 41.256759 ┆ -72.987472 │
│       ┆      ┆ SFTY STOR        ┆ DRIVE, 720       ┆   ┆       ┆        ┆           ┆            │
│ 4700  ┆ USA  ┆ YALE-TOUMEY      ┆ KEENE ROAD       ┆ … ┆ OO    ┆ OPEN   ┆ 42.838851 ┆ -72.351937 │
│       ┆      ┆ FOREST           ┆                  ┆   ┆       ┆        ┆           ┆            │
└───────┴──────┴──────────────────┴──────────────────┴───┴───────┴────────┴───────────┴────────────┘

In [7]:
building_sets

shape: (16, 6)
┌──────┬───────────────────────────┬───────────────┬──────────┬───────┬──────┐
│ bsID ┆ bsName                    ┆ bsDescription ┆ bsPublic ┆ owner ┆ sort │
│ ---  ┆ ---                       ┆ ---           ┆ ---      ┆ ---   ┆ ---  │
│ i64  ┆ str                       ┆ null          ┆ i64      ┆ str   ┆ i64  │
╞══════╪═══════════════════════════╪═══════════════╪══════════╪═══════╪══════╡
│ 2    ┆ Served By SPP             ┆ null          ┆ 1        ┆ sa    ┆ 60   │
│ 3    ┆ Served By CPP             ┆ null          ┆ 1        ┆ sa    ┆ 60   │
│ 4    ┆ Served By WPP             ┆ null          ┆ 1        ┆ sa    ┆ 60   │
│ 5    ┆ Served By CPP or SPP      ┆ null          ┆ 1        ┆ sa    ┆ 60   │
│ 20   ┆ Power Plants              ┆ null          ┆ 1        ┆ sa    ┆ 60   │
│ …    ┆ …                         ┆ …             ┆ …        ┆ …     ┆ …    │
│ 55   ┆ Academic & Admin: Small   ┆ null          ┆ 1        ┆ sa    ┆ 70   │
│ 56   ┆ YSM Laboratories          ┆ null          ┆ 1        ┆ sa    ┆ 70   │
│ 57   ┆ YSM Non Laboratories      ┆ null          ┆ 1        ┆ sa    ┆ 70   │
│ 58   ┆ West Campus               ┆ null          ┆ 1        ┆ sa    ┆ 70   │
│ 59   ┆ Not Served by Yale Plants ┆ null          ┆ 1        ┆ sa    ┆ 61   │
└──────┴───────────────────────────┴───────────────┴──────────┴───────┴──────┘

In [8]:
membership

shape: (975, 2)
┌───────┬──────┐
│ facid ┆ bsID │
│ ---   ┆ ---  │
│ str   ┆ i64  │
╞═══════╪══════╡
│ 0000  ┆ 59   │
│ 0110  ┆ 59   │
│ 0120  ┆ 59   │
│ 0122  ┆ 59   │
│ 0124  ┆ 59   │
│ …     ┆ …    │
│ 4270  ┆ 58   │
│ 4272  ┆ 4    │
│ 4272  ┆ 21   │
│ 4272  ┆ 58   │
│ 4700  ┆ 59   │
└───────┴──────┘

In [9]:
# Save to CSV
facilities.write_csv("../data/raw/facilities.csv")
building_sets.write_csv("../data/raw/building_sets.csv")
membership.write_csv("../data/raw/membership.csv")